---
- name: Clone {{ repo.url }}
  git:
    repo: "{{ repo.url }}"
    dest: "{{ repo.destination }}"
    version: "{{ repo.version }}"
    recursive: true
  tags: git
  when: (repo.public is defined) or (repo.public)

- block:
    - name: Ensure local clone directory exists
      file:
        state: directory
        path: "{{ sqitch_local_clone_directory }}"
        owner: "{{ sqitch_migrations_local_system_user }}"
        mode: "0644"
      delegate_to: 127.0.0.1
      become: false
    - name: Ensure local clone directory is empty
      file:
        state: absent
        path: "{{ sqitch_local_clone_directory }}"
        owner: "{{ sqitch_migrations_local_system_user }}"
      delegate_to: 127.0.0.1
      become: false
    - name: Clone {{ repo.url }} to local clone directory
      git:
        repo: "{{ repo.url }}"
        dest: "{{ sqitch_local_clone_directory }}"
        version: "{{ repo.version }}"
        recursive: true
      tags: git
      delegate_to: 127.0.0.1
      become: false
    - name: Copy repo to remote host
      copy:
        src: "{{ sqitch_local_clone_directory }}"
        dest: "{{ repo.destination }}"
        owner: "{{ sqitch_migrations_system_user }}"
        group: "{{ sqitch_migrations_system_group }}"
        mode: "0644"
    - name: Ensure local clone directory is empty
      file:
        state: absent
        path: "{{ sqitch_local_clone_directory }}"
        owner: "{{ sqitch_migrations_local_system_user }}"
      delegate_to: 127.0.0.1
      become: false
  when: not repo.public
